[gfs_settings.products.gfs_quarter_degree]
name = "gfs_quarter_degree"
filter = "filter_gfs_0p25.pl"
file = "gfs.t{cycle_hour_utc}z.pgrb2.0p25.anl"
dir = "/gfs.{date_utc}/{cycle_hour_utc}/atmos"

[gfs_queries.sailing_basic]
variables = "0x204000014400110280"
levels = "0x18000000000000001000000"

[gfs_data]
variables = [
    "4LFTX",
    "ABSV",
    "ACPCP",
    "ALBDO",
    "APCP",
    "CAPE",
    "CFRZR",
    "CICEP",
    "CIN",
    "CLWMR",
    "CNWAT",
    "CPOFP",
    "CPRAT",
    "CRAIN",
    "CSNOW",
    "CWAT",
    "CWORK",
    "DLWRF",
    "DPT",
    "DSWRF",
    "DZDT",
    "FLDCP",
    "FRICV",
    "GFLUX",
    "GRLE",
    "GUST",
    "HCDC",
    "HGT",
    "HINDEX",
    "HLCY",
    "HPBL",
    "ICAHT",
    "ICEC",
    "ICEG",
    "ICETK",
    "ICETMP",
    "ICMR",
    "LAND",
    "LCDC",
    "LFTX",
    "LHTFL",
    "MCDC",
    "MSLET",
    "O3MR",
    "PEVPR",
    "PLPL",
    "POT",
    "PRATE",
    "PRES",
    "PRMSL",
    "PWAT",
    "REFC",
    "REFD",
    "RH",
    "RWMR",
    "SFCR",
    "SHTFL",
    "SNMR",
    "SNOD",
    "SOILL",
    "SOILW",
    "SOTYP",
    "SPFH",
    "SUNSD",
    "TCDC",
    "TMAX",
    "TMIN",
    "TMP",
    "TOZNE",
    "TSOIL",
    "UFLX",
    "UGRD",
    "U-GWD",
    "ULWRF",
    "USTM",
    "USWRF",
    "VEG",
    "VFLX",
    "VGRD",
    "V-GWD",
    "VIS",
    "VRATE",
    "VSTM",
    "VVEL",
    "VWSH",
    "WATR",
    "WEASD",
    "WILT",
]
levels = [
    "0-0.1_m_below_ground",
    "0.1-0.4_m_below_ground",
    "0.4-1_m_below_ground",
    "1-2_m_below_ground",
    "0.995_sigma_level",
    "0.33-1_sigma_layer",
    "0.44-0.72_sigma_layer",
    "0.44-1_sigma_layer",
    "0.72-0.94_sigma_layer",
    "2_m_above_ground",
    "10_m_above_ground",
    "20_m_above_ground",
    "30_m_above_ground",
    "40_m_above_ground",
    "50_m_above_ground",
    "80_m_above_ground",
    "100_m_above_ground",
    "1000_m_above_ground",
    "4000_m_above_ground",
    "10_m_above_mean_sea_level",
    "1829_m_above_mean_sea_level",
    "2743_m_above_mean_sea_level",
    "3658_m_above_mean_sea_level",
    "3000-0_m_above_ground",
    "6000-0_m_above_ground",
    "180-0_mb_above_ground",
    "255-0_mb_above_ground",
    "90-0_mb_above_ground",
    "30-0_mb_above_ground",
    "0C_isotherm",
    "1_hybrid_level",
    "2_hybrid_level",
    "1000_mb",
    "975_mb",
    "950_mb",
    "925_mb",
    "900_mb",
    "850_mb",
    "800_mb",
    "750_mb",
    "700_mb",
    "650_mb",
    "600_mb",
    "550_mb",
    "500_mb",
    "450_mb",
    "400_mb",
    "350_mb",
    "300_mb",
    "250_mb",
    "200_mb",
    "150_mb",
    "100_mb",
    "70_mb",
    "50_mb",
    "40_mb",
    "30_mb",
    "20_mb",
    "15_mb",
    "10_mb",
    "7_mb",
    "5_mb",
    "3_mb",
    "2_mb",
    "1_mb",
    "0.7_mb",
    "0.4_mb",
    "0.2_mb",
    "0.1_mb",
    "0.07_mb",
    "0.04_mb",
    "0.02_mb",
    "0.01_mb",
    "surface",
    "max_wind",
    "mean_sea_level",
    "boundary_layer_cloud_layer",
    "planetary_boundary_layer",
    "tropopause",
    "entire_atmosphere",
    "entire_atmosphere_(considered_as_a_single_layer)",
    "top_of_atmosphere",
    "convective_cloud_layer",
    "convective_cloud_bottom_level",
    "convective_cloud_top_level",
    "high_cloud_layer",
    "high_cloud_bottom_level",
    "high_cloud_top_level",
    "low_cloud_layer",
    "low_cloud_bottom_level",
    "low_cloud_top_level",
    "middle_cloud_layer",
    "middle_cloud_bottom_level",
    "middle_cloud_top_level",
    "cloud_ceiling",
    "highest_tropospheric_freezing_level",
    "PV=-2e-06_(Km^2/kg/s)_surface",
    "PV=2e-06_(Km^2/kg/s)_surface",
]
